name: Build

on:
  push:
  pull_request:

jobs:
  build:
    uses: AwesomeHamster/workflows/.github/workflows/build.yml@master
    permissions:
      pull-requests: write
      issues: write
    with:
      lint: true
      test: true
      yarn-no-immutable: true
      approve: true
    secrets: inherit
