name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        koishi: ['4.15']

    steps:
      - uses: actions/checkout@v3
      - uses: AwesomeHamster/actions-test@master
        with:
          install-peer: koishi@${{ matrix.koishi }}
          test: |
            yarn lint
            yarn test
